# Assignment 3 - Text Analysis
An explanation this assignment could be found in the .pdf explanation document


## Materials to review for this assignment
<h4>From Moodle:</h4> 
<h5><u>Review the notebooks regarding the following python topics</u>:</h5>
<div class="alert alert-info">
&#x2714; <b>Working with strings</b> (tutorial notebook)<br/>
&#x2714; <b>Text Analysis</b> (tutorial notebook)<br/>
&#x2714; <b>Hebrew text analysis tools (tokenizer, wordnet)</b> (moodle example)<br/>
&#x2714; <b>(brief review) All previous notebooks</b><br/>
</div> 
<h5><u>Review the presentations regarding the following topics</u>:</h5>
<div class="alert alert-info">
&#x2714; <b>Text Analysis</b> (lecture presentation)<br/>
&#x2714; <b>(brief review) All other presentations</b><br/>
</div>

## Personal Details:

In [1]:
# Details Student 1:
#Teona Shiukashvili 332506401

# Details Student 2:


## Preceding Step - import modules (packages)
This step is necessary in order to use external modules (packages). <br/>

In [2]:
# --------------------------------------
import pandas as pd
import numpy as np
# --------------------------------------


# --------------------------------------
# ------------- visualizations:
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
# --------------------------------------


# ---------------------------------------
import sklearn
from sklearn import preprocessing, metrics, pipeline, model_selection, feature_extraction 
from sklearn import naive_bayes, linear_model, svm, neural_network, neighbors, tree
from sklearn import decomposition, cluster

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV 
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import mean_squared_error, r2_score, silhouette_score
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder

from sklearn.svm import LinearSVC
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron, SGDClassifier
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
# ---------------------------------------
from sklearn.feature_selection import SelectKBest, chi2

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC


# ----------------- output and visualizations: 
import warnings
from sklearn.exceptions import ConvergenceWarning
warnings.simplefilter("ignore")
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter("ignore", category=ConvergenceWarning)
# show several prints in one cell. This will allow us to condence every trick in one cell.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
%matplotlib inline
pd.pandas.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.3f' % x)
# ---------------------------------------

### Text analysis and String manipulation imports:

In [3]:
# --------------------------------------
# --------- Text analysis and Hebrew text analysis imports:
# vectorizers:
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# regular expressions:
import re
# --------------------------------------

### (optional) Hebrew text analysis - WordNet (for Hebrew)
Note: the WordNet is not a must

#### (optional) Only if you didn't install Wordnet (for Hebrew) use:

In [4]:
# word net installation:

# unmark if you want to use and need to install
!pip install wn
!python -m wn download omw-he:1.4


Cached file found: C:\Users\schi-\.wn_data\downloads\7ecf10e89326bc0ac26ad94b40fe60a7b6ac3302

Checking C:\Users\schi-\AppData\Local\Temp\tmpqx6wu4vj\omw-he\omw-he.xml
Skipping omw-he:1.4 (Hebrew Wordnet); already added



In [5]:
# word net import:

# unmark if you want to use:
import wn


### (optional) Hebrew text analysis - hebrew_tokenizer (Tokenizer for Hebrew)
Note: the hebrew_tokenizer is not a must

#### (optional) Only if you didn't install hebrew_tokenizer use:

In [6]:
# Hebrew tokenizer installation:

# unmark if you want to use and need to install:
!pip install hebrew_tokenizer

In [7]:
# Hebrew tokenizer import:

# unmark if you want to use:
import hebrew_tokenizer as ht

C:\Users\schi-\Matala3


### Reading input files
Reading input files for train annotated corpus (raw text data) corpus and for the test corpus

In [8]:
train_filename = 'annotated_corpus_for_train.csv'
test_filename  = 'corpus_for_test.csv'
df_train = pd.read_csv(train_filename, index_col=None, encoding='utf-8')
df_test  = pd.read_csv(test_filename, index_col=None, encoding='utf-8')

In [9]:
df_train.head(8)
df_train.shape

story gender
0  כשחבר הזמין אותי לחול, לא באמת חשבתי שזה יקרה,...      m
1  לפני שהתגייסתי לצבא עשיתי כל מני מיונים ליחידו...      m
2  מאז שהתחילו הלימודים חלומו של כל סטודנט זה הפנ...      f
3  כשהייתי ילד, מטוסים היה הדבר שהכי ריתק אותי. ב...      m
4  ‏הייתי מדריכה בכפר נוער ומתאם הכפר היינו צריכי...      f
5  לפני כ3 חודשים טסתי לרומא למשך שבוע. טסתי במטו...      f
6  אני כבר שנתיים נשוי והשנה אני ואישתי סוף סוף י...      m
7  השנה התחלנו שיפוץ בדירה שלנו בתל אביב. הדירה ה...      f

(753, 2)

In [10]:
df_test.head(3)
df_test.shape

test_example_id                                              story
0                0  כל קיץ אני והמשפחה נוסעים לארצות הברית לוס אנג...
1                1  הגעתי לשירות המדינה אחרי שנתיים כפעיל בתנועת "...
2                2  אחת האהבות הגדולות שלי אלו הכלבים שלי ושל אישת...

(323, 2)

### Your implementation:
Write your code solution in the following code-cells

# 1.Text Cleaning

In [11]:
# YOUR CODE HERE
def text_cleaning(text):
    text = re.sub(r'[^\w\s]', '', text)  #remove all the punctuation marks or special characters
    text = re.sub(r'\d+', '', text)      #remove all numbers
    text = re.sub(r'\s+', ' ', text)
    #text = text.lower()
#remove all multiple spaces
    return text

In [12]:
# Applying the text_cleaning function to the 'text_column' of dataframe 
def clear_df(df, column_name = 'story'):
    df[column_name] = df[column_name].apply(text_cleaning)
    return df

# 2. Vectorize 

In [13]:
# YOUR CODE HERE

#vectorize using the following methods:
#  TfidfVectorizer
#  CountVectorizer

df_c_train = clear_df(df_train)
df_c_test = clear_df(df_test)
vectorizer_tfidf = TfidfVectorizer(ngram_range=(1, 1), min_df=5)
train_tfidf = vectorizer_tfidf.fit_transform(df_c_train['story'])
y_train = df_c_train['gender']




In [14]:
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(train_tfidf.toarray())
X_train, X_test, y_train, y_test = train_test_split(X_train_scaled, y_train, test_size=0.2, random_state=42)


# 3.Models

In [15]:
models = [
    {
        'name': 'Logistic Regression',
        'classifier': LogisticRegression(),
        'params': {
            'clf__C': [0.1, 1, 10],
            'clf__solver': ['lbfgs', 'liblinear']
        }
    },
    {
        'name': 'Multinomial Naive Bayes',
        'classifier': MultinomialNB(),
        'params': {
            'clf__alpha': [0.1, 1, 10]
        }
    },
    {
        'name': 'Support Vector Machine',
        'classifier': SVC(),
        'params': {
            'clf__C': [0.1, 1, 10],
            'clf__kernel': ['linear', 'rbf']
        }
    },
     {
        'name': 'KNeighborsClassifier',
        'classifier': KNeighborsClassifier(),
        'params': {
            'clf__n_neighbors': [3, 5, 7, 9, 11],
            'clf__weights': ['uniform', 'distance'],
            'clf__leaf_size': [10, 20, 30, 40, 50],
            'clf__p': [1, 2]
        }
    },
     {
        'name': 'Perceptron',
        'classifier': Perceptron(),
        'params': {
            'clf__penalty': ['none', 'l2', 'l1', 'elasticnet'],
            'clf__alpha': [0.0001, 0.05]
        }
    }
]

# 4.Hyperparameter tuning and evaluation



In [20]:
from sklearn.metrics import make_scorer

#y_train = df_c_train['gender']

# Iterate through the models and perform hyperparameter tuning and evaluation
for model_info in models:
    print(f"Model: {model_info['name']}")
    
    
    pipeline = Pipeline([ # Adjust max_features as needed
        ('clf', model_info['classifier'])
    ])
    
    # Perform GridSearchCV for hyperparameter tuning
    grid_search = GridSearchCV(pipeline,model_info['params'], cv=5,n_jobs=-1)

    grid_search.fit(X_train, y_train)
    
    # Get the best parameters and estimator
    best_params = grid_search.best_params_
    best_estimator = grid_search.best_estimator_
    best_score = grid_search.best_score_
    model_info['best_params'] = grid_search.best_params_
    model_info['best_score'] = grid_search.best_score_
      # Perform cross-validation
    scores = cross_val_score(best_estimator, X_train, y_train, cv=10, scoring=make_scorer(f1_score, average='macro'))
    
    # Make predictions on the test data
    y_pred = best_estimator.predict(X_test)
    
    # Calculate the F1 score
    f1 = np.mean(scores)
    f1_m = f1_score(y_test, y_pred, pos_label='m')
    f1_f = f1_score(y_test, y_pred, pos_label='f')

    
    # Calculate the confusion matrix
    confusion_mat = confusion_matrix(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)

    
    print("Best Parameters: \n%s" % (best_params))
    print("Average F1 Score: %s" % (f1))
    print("F1 Male: %s" % (f1_m))
    print("F1 Female: %s" % (f1_f))
    print("Confusion matrix: \n%s" % (confusion_mat))
    print("Accuracy score: %s" %(accuracy))


Model: Logistic Regression


GridSearchCV(cv=5, estimator=Pipeline(steps=[('clf', LogisticRegression())]),
             n_jobs=-1,
             param_grid={'clf__C': [0.1, 1, 10],
                         'clf__solver': ['lbfgs', 'liblinear']})

Best Parameters: 
{'clf__C': 10, 'clf__solver': 'lbfgs'}
Average F1 Score: 0.5576787577082067
F1 Male: 0.8828125
F1 Female: 0.34782608695652173
Confusion matrix: 
[[  8  29]
 [  1 113]]
Accuracy score: 0.8013245033112583
Model: Multinomial Naive Bayes


GridSearchCV(cv=5, estimator=Pipeline(steps=[('clf', MultinomialNB())]),
             n_jobs=-1, param_grid={'clf__alpha': [0.1, 1, 10]})

Best Parameters: 
{'clf__alpha': 10}
Average F1 Score: 0.44783891216707306
F1 Male: 0.8603773584905661
F1 Female: 0.0
Confusion matrix: 
[[  0  37]
 [  0 114]]
Accuracy score: 0.7549668874172185
Model: Support Vector Machine


GridSearchCV(cv=5, estimator=Pipeline(steps=[('clf', SVC())]), n_jobs=-1,
             param_grid={'clf__C': [0.1, 1, 10],
                         'clf__kernel': ['linear', 'rbf']})

Best Parameters: 
{'clf__C': 1, 'clf__kernel': 'linear'}
Average F1 Score: 0.6063484246312197
F1 Male: 0.8809523809523809
F1 Female: 0.4
Confusion matrix: 
[[ 10  27]
 [  3 111]]
Accuracy score: 0.8013245033112583
Model: KNeighborsClassifier


GridSearchCV(cv=5, estimator=Pipeline(steps=[('clf', KNeighborsClassifier())]),
             n_jobs=-1,
             param_grid={'clf__leaf_size': [10, 20, 30, 40, 50],
                         'clf__n_neighbors': [3, 5, 7, 9, 11], 'clf__p': [1, 2],
                         'clf__weights': ['uniform', 'distance']})

Best Parameters: 
{'clf__leaf_size': 10, 'clf__n_neighbors': 3, 'clf__p': 2, 'clf__weights': 'distance'}
Average F1 Score: 0.4747877172789005
F1 Male: 0.8603773584905661
F1 Female: 0.0
Confusion matrix: 
[[  0  37]
 [  0 114]]
Accuracy score: 0.7549668874172185
Model: Perceptron


GridSearchCV(cv=5, estimator=Pipeline(steps=[('clf', Perceptron())]), n_jobs=-1,
             param_grid={'clf__alpha': [0.0001, 0.05],
                         'clf__penalty': ['none', 'l2', 'l1', 'elasticnet']})

Best Parameters: 
{'clf__alpha': 0.0001, 'clf__penalty': 'none'}
Average F1 Score: 0.6288473415235537
F1 Male: 0.8674698795180723
F1 Female: 0.3773584905660377
Confusion matrix: 
[[ 10  27]
 [  6 108]]
Accuracy score: 0.7814569536423841


In [31]:
best_model = SVC(kernel='linear', C=1, random_state=42)
# SVM is the best model that predicts male and woman.
best_model.fit(X_train, y_train)

y_pred = best_model.predict(X_test)


SVC(C=1, kernel='linear', random_state=42)

### Save output to csv (optional)
After you're done save your output to the 'classification_results.csv' csv file.<br/>
We assume that the dataframe with your results contain the following columns:
* column 1 (left column): 'test_example_id'  - the same id associated to each of the test stories to be predicted.
* column 2 (right column): 'predicted_category' - the predicted gender value for each of the associated story. 

Assuming your predicted values are in the `df_predicted` dataframe, you should save you're results as following:

In [ ]:
df_predicted.to_csv('classification_results.csv',index=False)